name: 9Xtream Quick Linker

on:
  workflow_dispatch:
    inputs:
      pairing_code:
        description: 'رمز الربط المتغير من شاشة التلفزيون'
        required: true
        type: string
      username:
        description: 'اسم المستخدم (Username)'
        required: true
        type: string
      password:
        description: 'كلمة المرور (Password)'
        required: true
        type: string

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Run Script
        env:
          INPUT_CODE: ${{ inputs.pairing_code }}
          INPUT_USER: ${{ inputs.username }}
          INPUT_PASS: ${{ inputs.password }}
        run: python script.py
