name: 9Xtream Auto Linker

on:
  workflow_dispatch:
    inputs:
      pairing_code:
        description: 'اكتب رمز الربط المتغير (مثل VWDS)'
        required: true
        type: string

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install easyocr playwright
          playwright install --with-deps chromium

      - name: Run Script
        env:
          INPUT_CODE: ${{ inputs.pairing_code }}
        run: python script.py
